# -*- coding: utf-8 -*-
"""streamlit_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17khDmJh2n3lg5LEBH3gOjFJq3ohfgqt1
"""

!git clone https://github.com/edgi-govdata-archiving/ECHO_modules.git &>/dev/null;
import pandas as pd

#https://docs.streamlit.io/library/get-started/create-an-app
from ECHO_modules.get_data import get_echo_data
sql= 'select * from "ECHO_EXPORTER" where "FAC_CITY" = \'PEEKSKILL\''
def load_data(sql):
  data = get_echo_data(sql)
  data["LAT"] = data["FAC_LAT"]
  data["LON"] = data["FAC_LONG"]
  return data
data_load_state = st.text('Loading data...')
data = load_data(sql)
data_load_state.text('Loading data...done!')
st.map(data)

