# -*- coding: utf-8 -*-
"""streamlit_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17khDmJh2n3lg5LEBH3gOjFJq3ohfgqt1
"""

#https://docs.streamlit.io/library/get-started/create-an-app
import pandas as pd
import urllib.parse

sql= 'select * from "ECHO_EXPORTER" where "FAC_CITY" = \'PEEKSKILL\''

def load_data(sql):
  url= 'https://portal.gss.stonybrook.edu/echoepa/?query='
  data_location = url + urllib.parse.quote_plus(sql) + '&pg'
  data = pd.read_csv(data_location,encoding='iso-8859-1', dtype={"REGISTRY_ID": "Int64"}
  data["LAT"] = data["FAC_LAT"]
  data["LON"] = data["FAC_LONG"]
  return data

data_load_state = st.text('Loading data...')
data = load_data(sql)
data_load_state.text('Loading data...done!')

st.map(data)

